apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cool-users-sql
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cool-users-sql
  targetCPUUtilizationPercentage: 20 # target CPU utilization