apiVersion: v1
kind: Service
metadata:
  name: cool-users-sql
  labels:
    app: cool-users-sql
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: cool-users-sql